# Generated by Django 5.0.1 on 2024-03-05 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="student",
            name="institution",
        ),
    ]
