# Generated by Django 5.0.1 on 2024-04-28 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0003_alter_community_name_alter_course_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseDepartmentLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="admin.course"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin.department",
                    ),
                ),
            ],
            options={
                "db_table": "course_department_link",
            },
        ),
        migrations.AddConstraint(
            model_name="coursedepartmentlink",
            constraint=models.UniqueConstraint(
                fields=("course", "department"), name="unique_course_department_link"
            ),
        ),
    ]
