# Generated by Django 5.0.1 on 2024-04-28 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0004_coursedepartmentlink_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="department",
        ),
    ]
