# Generated by Django 5.0.1 on 2024-05-09 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0006_institutioncourselink_institutiondepartmentlink_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institution",
            old_name="instituion_type",
            new_name="institution_type",
        ),
    ]
