# Generated by Django 5.0.1 on 2024-02-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_verificationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationtoken",
            name="token_type",
            field=models.CharField(
                choices=[("verify", "verify"), ("forgot", "forgot")],
                default="verify",
                max_length=7,
            ),
            preserve_default=False,
        ),
    ]
