# Generated by Django 5.0.1 on 2024-04-15 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0002_initial"),
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercommunitylink",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercommunitylink",
            name="role",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.role"
            ),
        ),
        migrations.AddField(
            model_name="userinstitutionlink",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userinstitutionlink",
            name="role",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.role"
            ),
        ),
        migrations.AddConstraint(
            model_name="usercommunitylink",
            constraint=models.UniqueConstraint(
                fields=("user", "community"), name="unique_user_community"
            ),
        ),
        migrations.AddConstraint(
            model_name="userinstitutionlink",
            constraint=models.UniqueConstraint(
                fields=("user", "institution"), name="unique_user_institution"
            ),
        ),
    ]
