# Generated by Django 5.0.1 on 2024-02-27 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_resetformtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationtoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="ResetFormToken",
        ),
        migrations.DeleteModel(
            name="VerificationToken",
        ),
    ]
