# Generated by Django 5.0.1 on 2024-03-05 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0002_remove_faculty_institution_and_more"),
        ("users", "0006_verificationtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCommunityLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_user_link",
                        to="admin.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_community_link",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_community_link",
            },
        ),
        migrations.CreateModel(
            name="UserInstitutionLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_user_link",
                        to="admin.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_institution_link",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_institution_link",
            },
        ),
    ]
