# Generated by Django 5.0.1 on 2024-03-09 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admin", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_number", models.IntegerField()),
                ("question", models.CharField(max_length=500)),
                (
                    "question_type",
                    models.CharField(
                        choices=[("MCQ", "mcq"), ("DIRECT", "direct")], max_length=6
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "question",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "answer_number",
                    models.IntegerField(
                        choices=[
                            ("PLAIN", 0),
                            ("A", 1),
                            ("B", 2),
                            ("C", 3),
                            ("D", 4),
                            ("E", 5),
                        ]
                    ),
                ),
                ("answer", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_viva.question",
                    ),
                ),
            ],
            options={
                "db_table": "answer",
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "question_bank",
            },
        ),
        migrations.CreateModel(
            name="QBankCourseLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="admin.course"
                    ),
                ),
                (
                    "question_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_viva.questionbank",
                    ),
                ),
            ],
            options={
                "db_table": "qbank_course_link",
            },
        ),
        migrations.CreateModel(
            name="QuestionModuleLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="admin.module"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_viva.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_module_link",
            },
        ),
        migrations.CreateModel(
            name="QuizOrViva",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                (
                    "viva_or_quiz",
                    models.CharField(
                        choices=[("VIVA", "viva"), ("QUIZ", "quiz")], max_length=4
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conductor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "quiz_or_viva",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="viva_or_quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz_viva.quizorviva"
            ),
        ),
        migrations.AddConstraint(
            model_name="qbankcourselink",
            constraint=models.UniqueConstraint(
                fields=("question_bank", "course"), name="unique_course_question_bank"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionmodulelink",
            constraint=models.UniqueConstraint(
                fields=("question", "module"), name="unique_question_module"
            ),
        ),
    ]
