# Generated by Django 5.0.1 on 2024-02-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VivaOrQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('viva_quiz_type', models.CharField(choices=[('VIVA', 'Viva'), ('QUIZ', 'Quiz')], max_length=4)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('MCQ', 'mcq'), ('DIRECT', 'direct')], max_length=6)),
                ('viva_or_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_viva.vivaorquiz')),
            ],
        ),
    ]
