# Generated by Django 5.0.1 on 2024-03-05 16:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_viva", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=36, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="vivaorquiz",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=36, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="vivaorquiz",
            name="viva_quiz_type",
            field=models.CharField(
                choices=[("VIVA", "viva"), ("QUIZ", "quiz")], max_length=4
            ),
        ),
        migrations.AlterModelTable(
            name="question",
            table="question",
        ),
        migrations.AlterModelTable(
            name="vivaorquiz",
            table="viva_or_quiz",
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "answer_number",
                    models.IntegerField(
                        choices=[
                            ("PLAIN", 0),
                            ("A", 1),
                            ("B", 2),
                            ("C", 3),
                            ("D", 4),
                            ("E", 5),
                        ]
                    ),
                ),
                ("answer", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_viva.question",
                    ),
                ),
            ],
            options={
                "db_table": "answer",
            },
        ),
    ]
