# Generated by Django 5.0.1 on 2024-04-27 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_viva", "0001_initial"),
        ("users", "0003_usercommunitylink_accepted_usercommunitylink_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="viva_or_quiz",
        ),
        migrations.AddField(
            model_name="question",
            name="qbank",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz_viva.questionbank",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quizorviva",
            name="duration",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quizorviva",
            name="end_time",
            field=models.DateTimeField(default="2024-04-27 17:29:00.000000+00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quizorviva",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizorviva",
            name="start_time",
            field=models.DateTimeField(default="2024-04-27 17:29:00.000000+00:00"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CommunityMemberQuizOrVivaLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "community_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
                (
                    "quiz_or_viva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_viva.quizorviva",
                    ),
                ),
            ],
            options={
                "db_table": "community_member_quiz_or_viva_link",
            },
        ),
        migrations.CreateModel(
            name="StudentQuizOrVivaLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz_or_viva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_viva.quizorviva",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "student_quiz_or_viva_link",
            },
        ),
        migrations.AddConstraint(
            model_name="communitymemberquizorvivalink",
            constraint=models.UniqueConstraint(
                fields=("community_member", "quiz_or_viva"),
                name="unique_community_member_quiz_or_viva",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentquizorvivalink",
            constraint=models.UniqueConstraint(
                fields=("student", "quiz_or_viva"), name="unique_student_quiz_or_viva"
            ),
        ),
    ]
