# Generated by Django 5.0.1 on 2024-05-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_viva", "0002_remove_question_viva_or_quiz_question_qbank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
