# Generated by Django 5.0.1 on 2024-05-11 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_viva", "0004_quizorviva_qbank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Options",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option_number",
                    models.IntegerField(
                        choices=[
                            ("PLAIN", 0),
                            ("A", 1),
                            ("B", 2),
                            ("C", 3),
                            ("D", 4),
                            ("E", 5),
                        ]
                    ),
                ),
                ("option", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_viva.question",
                    ),
                ),
            ],
            options={
                "db_table": "options",
            },
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
