# Generated by Django 5.0.1 on 2024-05-11 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0008_coursefacultylink_unique_course_faculty_link"),
        ("quiz_viva", "0005_options_delete_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="module",
            field=models.ForeignKey(
                default="23412-1234-123",
                on_delete=django.db.models.deletion.CASCADE,
                to="admin.module",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="QuestionModuleLink",
        ),
    ]
