# Generated by Django 5.0.1 on 2024-05-11 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_viva", "0006_question_module_delete_questionmodulelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentquizorvivalink",
            name="malpractice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentquizorvivalink",
            name="marks_obtained",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentquizorvivalink",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="studentquizorvivalink",
            name="total_marks",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="StudentResponse",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_viva.options",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_viva.question",
                    ),
                ),
                (
                    "student_quiz_or_viva_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_viva.studentquizorvivalink",
                    ),
                ),
            ],
            options={
                "db_table": "student_response",
            },
        ),
        migrations.AddConstraint(
            model_name="studentresponse",
            constraint=models.UniqueConstraint(
                fields=("student_quiz_or_viva_link", "question"),
                name="unique_student_response",
            ),
        ),
    ]
