# Generated by Django 5.0.1 on 2024-05-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_viva", "0007_studentquizorvivalink_malpractice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="options",
            name="option_number",
            field=models.CharField(
                choices=[
                    ("PLAIN", 0),
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                ],
                max_length=5,
            ),
        ),
    ]
