# Generated by Django 5.0.1 on 2024-05-12 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_viva", "0008_alter_options_option_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizorviva",
            name="description",
        ),
    ]
